/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32_f446xx.h"
#define LED_PIN		5
#define BUTTON_PIN	13

int main(void)
{
	GPIOA_CLK_EN();		//Enable GPIOA Clock
	GPIOC_CLK_EN();		//Enable GPIOC Clock

	GPIOA->MODER &= ~(0x3 << (LED_PIN * 2));		// Clear mode bits for PA5
	GPIOA->MODER |= (0x1<<(LED_PIN*2));				// Set PA5 as output mode
	GPIOC->MODER &= ~(0x3 << (BUTTON_PIN * 2));		// Set the pin as input by clearing its MODER bits (00 = Input mode)
	GPIOA->OTYPER &= ~(0x1<<LED_PIN);				// Set PA5 as push-pull output

	GPIOA->OSPEEDR &= ~(0x3 << (LED_PIN*2));		// Clear speed bits
	GPIOA->OSPEEDR |= (0x1<<(LED_PIN*2));			// Set medium speed for PA5

	GPIOA->PUPDR &= ~(0x3 << (LED_PIN*2));			// No pull-up/pull-down for PA5
	GPIOC->PUPDR &= ~(0x3 << (LED_PIN*2));			// Clear existing pull-up/pull-down configuration for the pin
	GPIOC->PUPDR |= (0x1 << (LED_PIN*2));			// Enable pull-up resistor for the pin (01 = Pull-up)

	while(1)
	{
		if(!(GPIOC->IDR & (1 << BUTTON_PIN))) {		// Check if button is pressed (active low)
			GPIOA->ODR |= (1<<LED_PIN);				// Turn ON LED at PA5
		} else {
			GPIOA->ODR &= ~(1<<LED_PIN);			// Turn OFF LED at PA5
		}
	}
}
